import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "CUET Teachers Association",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
        <nav className="nav-bar">
          <Link href="/teacher/vote" className="nav-link">
            Vote
          </Link>
          <Link href="/teacher/schedule" className="nav-link">
            Schedule
          </Link>
          <Link href="/teacher/profile" className="nav-link">
            Profile
          </Link>
          <Link href="/teacher/event" className="nav-link">
            Event
          </Link>
        </nav>
      </body>
    </html>
  );
}
