import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "CUET Teachers Association",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
